### ISSUE TITLE
I appreciate the small updates

### ISSUE THREAD

**Issue by kerneljay** [Sleepless-Development/sleepless_pedmanager#2]
Could you potentially make it so a ped doesn't have to spawn. Make it so you can add custom markers anywhere

**Comment by DemiAutomatic** [comment]
I certainly could. That seems like maybe its outside the scope of the pedmanager though. So if i was to go this route i would consider possibly making the textui a utility script on its own with exports to add entities or coords

**Comment by kerneljay** [comment]
I am currently working on adding exports. I have added a addMarker and removeMarker exports. Working fine but just a couple bugs which I am working on currently. I will push the pull request once completed. Thanks for the amazing resource 🗡️ Inspired me to work on more UI

**Comment by DemiAutomatic** [comment]
Thats awesome, but honestly i wouldn't add something like that inside the scope of the pedmanager since it has nothing to do with it. so i will likely create a separate resource specifically for the textui. and utilize exports in my pedmanager resource

**Comment by kerneljay** [comment]
Or you could just make it one resource?! lol

Allow peds and also have the exports on the side for adding markers

**Comment by DemiAutomatic** [comment]
I definitely understand that i could, i just feel that adding the additional functionality splits the focus of the resource and logically makes little sense to call an export from a ped manager to add an arbitrary point of interaction somewhere. purpose built and limited in focus is just better for me personally. maybe i can repurpose the focus of the script from being a ped manager to being an interaction utility. Basically exactly what you are saying, but i would rebrand it to be more focused on interactions in general rather than just being a ped manager. The peds will just be part of the interaction utility. So ultimately i think you're correct

**Comment by kerneljay** [comment]
Appreciate your reply and I understand completely!
